name = "LightControl"
version = "0.1.0"
license = "MIT"
author = "Jean-Christophe Loiseau"
maintainer = "jean-christophe.loiseau@ensam.eu"
copyright = "Copyright 2023, Jean-Christophe Loiseau"
description = ""

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

[dependencies]
stdlib = "*"
assert = {git="https://github.com/BerkeleyLab/assert.git"}

[dev-dependencies]
test-drive.git = "https://github.com/nekStab/test-drive.git"
FACE = {git="https://github.com/szaghi/FACE.git"}

[[example]]

name = "oscillator"
source-dir = "example/oscillator"
